### ISSUE TITLE
Using modified version of Diffbind

### ISSUE THREAD

**Issue by bioinfouser** [andrewholding/Brundle_Example#1]
Hello Dr. Holding,

Could you please explain the reason why you used modified version of Diffbind? Then the latest version of Diffbind is not usable, right?

**Comment by andrewholding** [comment]
The devel version of DiffBind in bioconductor has been patched to allow editing of the data structure and will be included in the next bioconductor release. Until then you can use the modified version we provide. 

Does that solve your question?

**Comment by bioinfouser** [comment]
All perfect! Thank you for your quick reply!
