### ISSUE TITLE
How is workflow.svg generated?

### ISSUE THREAD

**Issue by YichaoOU** [andrewholding/Brundle_Example#3]
The pipeline figure looks really nice. Can you tell me how it was generated?

Thanks,
Yichao

**Comment by andrewholding** [comment]
Hi Yichao,

Sorry to disappoint but in power point! It's just boxes, lines and the odd
circle.

Andy

**Comment by andrewholding** [comment]
[workflow.pptx](https://github.com/andrewholding/Brundle_Example/files/3263724/workflow.pptx)

**Comment by YichaoOU** [comment]
Thanks for the quick response! I thought it was generated by some program.
